packages:
  - apps/*
  - packages/*
minimumReleaseAgeExclude:
  - eve@0.11.4
  - '@next/env@16.3.6'
  - '@next/eslint-plugin-next@16.3.6'
  - '@next/swc-darwin-arm64@16.3.6'
  - '@next/swc-darwin-x64@16.3.6'
  - '@next/swc-linux-arm64-gnu@16.3.6'
  - '@next/swc-linux-arm64-musl@16.3.6'
  - '@next/swc-linux-x64-gnu@16.3.6'
  - '@next/swc-linux-x64-musl@16.3.6'
  - '@next/swc-win32-arm64-msvc@16.3.6'
  - '@next/swc-win32-x64-msvc@16.3.6'
  - eslint-config-next@16.3.6
  - next@16.3.6
overrides:
  ai: 7.0.0-beta.178
allowBuilds:
  '@swc/core': true
  cbor-extract: true
  esbuild: true
  unrs-resolver: true
